# -*- coding: utf-8 -*-
"""0001 · NBIS 第一轮逐字段填充（registry 口径 / fct 期间与快照 / 边机制与证据 / 来源 / 实体）· owner B · 2026-09-20
新增 18 条一手记录（Nebius Q2 / Q1 2026 股东信），1 条取代（r013 → r203），268 个字段填充。
注：原 enrich/updates.csv 283 行里有 17 行写错了表（如 fct_quant r203，而 r203 路由在 fct_opinion），旧加载器 UPDATE 0 行静默通过；migrate.py 主键不存在即拒绝，这里已剔除 15 行、改表 2 行。
快照：snapshots/snap_nebius_shl_q2_2026.txt · snap_nebius_shl_q1_2026.txt
每个 set() 的 basis 是该值的依据（原文 / 快照 / doc 编号 / 规则），应用时连同改前值进 change_log。"""
OWNER = 'B'
SHL_Q2 = 'Nebius Q2 2026 Shareholder Letter https://assets.nebius.com/assets/a6ecfd85-a6cb-4967-8ef7-9a25bd261f9c/SHLQ226.pdf'
SHL_Q1 = 'Nebius Q1 2026 Shareholder Letter https://assets.nebius.com/assets/aa1bc2e6-df83-40cd-a6a2-95e7cda3d16c/Nebius%20SHL_Q1%202026.pdf'

def up(m):
    # ---- 新增记录：等价于在 13-观测记录.csv 追加一行；路由 / 来源 / 方向由 core 规则自动完成 ----
    m.observe('r201', 'm_nbis_rev', 'NBIS', 'actual', '575', 'USD M AI cloud 收入', '2026Q2', '2026-08-12', SHL_Q2, 'P1',
              note='YoY +514%；“Nebius AI cloud revenue grew 514% year-over-year to $575 million”')
    m.observe('r202', 'm_nbis_ebitda', 'NBIS', 'actual', '285.7', 'USD M AI cloud Adj. EBITDA', '2026Q2', '2026-08-12', SHL_Q2, 'P1',
              note='利润率 49.7%；“AI cloud business … generated adjusted EBITDA of $285.7 million and adjusted EBITDA margin of 49.7%”')
    m.observe('r203', 'm_nbis_calltone', 'NBIS', 'actual', '49.7%', 'AI cloud Adj. EBITDA 利润率', '2026Q2', '2026-08-12', SHL_Q2, 'P1',
              note='取代 r013（P2 转述 ~50%）；“adjusted EBITDA margin of 49.7%”')
    m.observe('r204', 'm_nbis_backlog', 'NBIS', 'actual', '5.7', 'USD B capex', '2026Q2', '2026-08-12', SHL_Q2, 'P1',
              note='“In Q2’26, capital expenditures were approximately $5.7 billion, primarily driven by purchases of GPUs and GPU-related hardware”')
    m.observe('r205', 'm_nbis_backlog', 'NBIS', 'actual', '8', 'USD B 现金', '2026-06-30', '2026-08-12', SHL_Q2, 'P1',
              note='“Strong cash position ending Q2 … $8B cash, including $2.3 billion in positive operating cash flow”')
    m.observe('r206', 'm_nbis_backlog', 'NBIS', 'event', '首笔担保债 $775M @ SOFR+2.50%，以已部署 GPU 与投资级客户合同现金流作抵押', 'USD M', '2026-07', '2026-08-12', SHL_Q2, 'P1',
              note='“In July we entered into our first secured debt financing, raising $775 million priced at SOFR + 2.50%”；同季启用 ATM')
    m.observe('r207', 'm_nbis_backlog', 'NBIS', 'state', '四笔里程碑合同，平均 TCV >$1B；capex 50–60% 由预付自筹', '—', '2026Q2', '2026-08-12', SHL_Q2, 'P1',
              note='“four landmark deals, which averaged more than $1 billion in TCV each”；“50-60% of capex self-financed by prepayments”')
    m.observe('r208', 'm_nbis_calltone', 'NBIS', 'actual', '+30%', '老一代 GPU 定价 vs Q1', '2026Q2', '2026-08-12', SHL_Q2, 'P1',
              note='“more than 30% higher pricing on older-generation GPUs versus Q1”')
    m.observe('r209', 'm_nbis_capacity', 'NBIS', 'event', 'Q3 签下首单短期容量合同（3–6 个月、溢价定价），Q4 上线；首次容量拍卖试点清出 Blackwell 最高价', '—', '2026Q3', '2026-08-12', SHL_Q2, 'P1',
              note='“In Q3, we closed our first short-term capacity deal … expected to go live in Q4”；“first capacity auction pilot … highest price we have cleared for NVIDIA Blackwell chips to date”')
    m.observe('r210', 'm_nbis_capacity', 'NBIS', 'target', '>1', 'GW / 年 新增部署', '2027 起', '2026-08-12', SHL_Q2, 'P1',
              note='“we plan to deploy more than 1 GW per year, starting in 2027”')
    m.observe('r211', 'm_nbis_capacity', 'NBIS', 'event', 'Q2 新增合同站点：英国、爱沙尼亚、芬兰；美国自有 AI factory 在建', '—', '2026Q2', '2026-08-12', SHL_Q2, 'P1',
              note='“additional sites in the UK, Estonia and Finland. Construction is also underway at some of our owned AI factories in the US”')
    m.observe('r212', 'm_nbis_backlog', 'NBIS', 'state', '点名客户：Reflection、Cohere、Cognition、Core Automation、Higgsfield（用量 >20x）、Recraft、Revolut、AMI、Basecamp Research', '—', '2026Q2', '2026-08-12', SHL_Q2, 'P1',
              note='客户集中度与质量的一手名单；Higgsfield “expanded its usage on the platform by >20x”')
    m.observe('r213', 'm_nbis_rev', 'NBIS', 'prior', '399.0', 'USD M', '2026Q1', '2026-05-13', SHL_Q1, 'P1',
              note='“Q1 group revenue of $399.0 million exceeded our expectations”')
    m.observe('r214', 'm_nbis_rev', 'NBIS', 'prior', '389.7', 'USD M AI cloud 收入', '2026Q1', '2026-05-13', SHL_Q1, 'P1',
              note='“Nebius AI cloud revenue was $389.7 million in Q1’26, an 841%” YoY')
    m.observe('r215', 'm_nbis_arr', 'NBIS', 'prior', '1.92', 'USD B', '2026-03-31', '2026-05-13', SHL_Q1, 'P1',
              note='“Annualized run-rate revenue (ARR) of $1.92 billion”')
    m.observe('r216', 'm_nbis_ebitda', 'NBIS', 'prior', '129.5', 'USD M', '2026Q1', '2026-05-13', SHL_Q1, 'P1',
              note='“Group adjusted EBITDA of $129.5 million in Q1”；AI cloud 分部 $174.0M')
    m.observe('r217', 'm_nbis_backlog', 'NBIS', 'prior', '2.5', 'USD B capex', '2026Q1', '2026-05-13', SHL_Q1, 'P1',
              note='“In Q1’26, capital expenditures were approximately $2.5 billion”')
    m.observe('r218', 'm_nbis_capacity', 'NBIS', 'prior', '3', 'GW 合同电力（contracted power）', '2026 年底目标（Q1 版）', '2026-05-13', SHL_Q1, 'P1',
              note='Q1 目标 3 GW → Q2 上调至 +4 GW → 5 GW；“contracted power target of 3 GW”')
    # ---- 取代：旧行不删 ----
    m.supersede('r013', 'r203', reason='P2 转述 ~50% 被股东信一手 49.7% 取代')
    # ---- metric_registry（42 个字段）----
    m.set('metric_registry', 'm_nbis_rev', 'track', 'neocloud', basis='doc22 §二')
    m.set('metric_registry', 'm_nbis_rev', 'kou_jing', '美元；季度 GAAP 收入；另记 AI cloud 分部收入（unit 区分）', basis='SHL Q2 定义 / doc22')
    m.set('metric_registry', 'm_nbis_rev', 'unit', 'USD M', basis='记录单位')
    m.set('metric_registry', 'm_nbis_rev', 'source_ids', '["src_nebius_6_k_ex_99_1","src_nebius_q2_2026_shareholder_letter"]', basis='source_master')
    m.set('metric_registry', 'm_nbis_rev', 'upstream_deps', '[]', basis='doc25 链式图')
    m.set('metric_registry', 'm_nbis_rev', 'last_validated', '2026-09-20', basis='本轮逐字段核 SHL 原文')
    m.set('metric_registry', 'm_nbis_ebitda', 'track', 'neocloud', basis='doc22 §二')
    m.set('metric_registry', 'm_nbis_ebitda', 'kou_jing', 'Adjusted EBITDA = GAAP 净利润 + 折旧摊销 + 利息 + 税 + SBC 等（SHL 附注定义）；另记 AI cloud 分部', basis='SHL Q2 定义 / doc22')
    m.set('metric_registry', 'm_nbis_ebitda', 'unit', 'USD M', basis='记录单位')
    m.set('metric_registry', 'm_nbis_ebitda', 'source_ids', '["src_nebius_6_k_ex_99_1","src_nebius_q2_2026_shareholder_letter"]', basis='source_master')
    m.set('metric_registry', 'm_nbis_ebitda', 'upstream_deps', '[]', basis='doc25 链式图')
    m.set('metric_registry', 'm_nbis_ebitda', 'last_validated', '2026-09-20', basis='本轮逐字段核 SHL 原文')
    m.set('metric_registry', 'm_nbis_arr', 'track', 'neocloud', basis='doc22 §二')
    m.set('metric_registry', 'm_nbis_arr', 'kou_jing', 'ARR = AI cloud 季末最后一月收入 × 12（SHL 脚注）', basis='SHL Q2 定义 / doc22')
    m.set('metric_registry', 'm_nbis_arr', 'unit', 'USD B', basis='记录单位')
    m.set('metric_registry', 'm_nbis_arr', 'source_ids', '["src_nebius_q2_2026_shareholder_letter"]', basis='source_master')
    m.set('metric_registry', 'm_nbis_arr', 'upstream_deps', '["m_nbis_rev"]', basis='doc25 链式图')
    m.set('metric_registry', 'm_nbis_arr', 'last_validated', '2026-09-20', basis='本轮逐字段核 SHL 原文')
    m.set('metric_registry', 'm_nbis_backlog', 'track', 'neocloud', basis='doc22 §二')
    m.set('metric_registry', 'm_nbis_backlog', 'kou_jing', '客户承诺（customer commitments，multi-year 合同总额上限，非 GAAP backlog）；客户预付为年度指引；另记 capex / 现金 / 融资事件', basis='SHL Q2 定义 / doc22')
    m.set('metric_registry', 'm_nbis_backlog', 'unit', 'USD B', basis='记录单位')
    m.set('metric_registry', 'm_nbis_backlog', 'source_ids', '["src_nebius_q2_2026_shareholder_letter","src_nbis_q2_电话会_transcript_the_globe_and_mail_转载"]', basis='source_master')
    m.set('metric_registry', 'm_nbis_backlog', 'upstream_deps', '["m_lab_funding_reflection","m_lab_funding_cohere"]', basis='doc25 链式图')
    m.set('metric_registry', 'm_nbis_backlog', 'last_validated', '2026-09-20', basis='本轮逐字段核 SHL 原文')
    m.set('metric_registry', 'm_nbis_capacity', 'track', 'neocloud', basis='doc22 §二')
    m.set('metric_registry', 'm_nbis_capacity', 'kou_jing', '合同电力 contracted power（已锁定土地与电力承诺）≠ 并网电力 connected power（可上架）；两口径分别记', basis='SHL Q2 定义 / doc22')
    m.set('metric_registry', 'm_nbis_capacity', 'unit', 'GW / MW', basis='记录单位')
    m.set('metric_registry', 'm_nbis_capacity', 'source_ids', '["src_nebius_q2_2026_shareholder_letter","src_nebius_q1_2026_shareholder_letter"]', basis='source_master')
    m.set('metric_registry', 'm_nbis_capacity', 'upstream_deps', '["m_dc_power_iea","m_energy_grid"]', basis='doc25 链式图')
    m.set('metric_registry', 'm_nbis_capacity', 'last_validated', '2026-09-20', basis='本轮逐字段核 SHL 原文')
    m.set('metric_registry', 'm_nbis_calltone', 'track', 'neocloud', basis='doc22 §二')
    m.set('metric_registry', 'm_nbis_calltone', 'kou_jing', '管理层表述抽取：ACV/MW、新一代定价、利润率、capex 指引；codebook icl-v1', basis='SHL Q2 定义 / doc22')
    m.set('metric_registry', 'm_nbis_calltone', 'unit', '混合', basis='记录单位')
    m.set('metric_registry', 'm_nbis_calltone', 'source_ids', '["src_nebius_q2_2026_shareholder_letter","src_nbis_q2_电话会_transcript_the_globe_and_mail_转载"]', basis='source_master')
    m.set('metric_registry', 'm_nbis_calltone', 'upstream_deps', '[]', basis='doc25 链式图')
    m.set('metric_registry', 'm_nbis_calltone', 'last_validated', '2026-09-20', basis='本轮逐字段核 SHL 原文')
    m.set('metric_registry', 'm_reconcile_nbis', 'track', 'neocloud', basis='doc22 §二')
    m.set('metric_registry', 'm_reconcile_nbis', 'kou_jing', '供给态（本体 + 光模块 + capex）× 需求态（lab 融资 / 合同 / 能力）→ 信念 / 观察 / 泡沫预警；阈值 C6 未定', basis='SHL Q2 定义 / doc22')
    m.set('metric_registry', 'm_reconcile_nbis', 'unit', '三态', basis='记录单位')
    m.set('metric_registry', 'm_reconcile_nbis', 'source_ids', '[]', basis='source_master')
    m.set('metric_registry', 'm_reconcile_nbis', 'upstream_deps', '["m_nbis_capacity","m_cn_optics_zte","m_hyperscaler_capex","m_lab_funding_reflection","m_lab_funding_frontier","m_circular_financing"]', basis='doc25 链式图')
    m.set('metric_registry', 'm_reconcile_nbis', 'last_validated', '2026-09-20', basis='本轮逐字段核 SHL 原文')
    # ---- entity_master（2 个字段）----
    m.set('entity_master', 'ent_nbis', 'aliases', '["Nebius","Nebius Group N.V.","NBIS","前 Yandex N.V."]', basis='公司资料')
    m.set('entity_master', 'ent_nbis', 'status', 'reviewed', basis='两轴 L2 / public 无争议', owner='D')
    # ---- fct_quant（81 个字段）----
    m.set('fct_quant', 'r001', 'period_start', '2026-04-01', basis='期间解析')
    m.set('fct_quant', 'r001', 'period_end', '2026-06-30', basis='期间解析')
    m.set('fct_quant', 'r003', 'period_start', '2026-04-01', basis='期间解析')
    m.set('fct_quant', 'r003', 'period_end', '2026-06-30', basis='期间解析')
    m.set('fct_quant', 'r004', 'period_start', '2026-06-30', basis='期间解析')
    m.set('fct_quant', 'r004', 'period_end', '2026-06-30', basis='期间解析')
    m.set('fct_quant', 'r002', 'period_start', '2026-01-01', basis='期间解析')
    m.set('fct_quant', 'r002', 'period_end', '2026-12-31', basis='期间解析')
    m.set('fct_quant', 'r005', 'period_start', '2026-01-01', basis='期间解析')
    m.set('fct_quant', 'r005', 'period_end', '2026-12-31', basis='期间解析')
    m.set('fct_quant', 'r008', 'period_start', '2026-12-31', basis='期间解析')
    m.set('fct_quant', 'r008', 'period_end', '2026-12-31', basis='期间解析')
    m.set('fct_quant', 'r002', 'snapshot_id', 'snap_nebius_shl_q2_2026', basis='pipeline/snapshots/')
    m.set('fct_quant', 'r003', 'snapshot_id', 'snap_nebius_shl_q2_2026', basis='pipeline/snapshots/')
    m.set('fct_quant', 'r004', 'snapshot_id', 'snap_nebius_shl_q2_2026', basis='pipeline/snapshots/')
    m.set('fct_quant', 'r005', 'snapshot_id', 'snap_nebius_shl_q2_2026', basis='pipeline/snapshots/')
    m.set('fct_quant', 'r008', 'snapshot_id', 'snap_nebius_shl_q2_2026', basis='pipeline/snapshots/')
    m.set('fct_quant', 'r001', 'anchor', 'Revenues … 582.3（Ex.99.1 表）', basis='6-K 原文')
    m.set('fct_quant', 'r003', 'anchor', 'Adjusted EBITDA … 236.2；as a percentage of revenues 41%', basis='SHL 表')
    m.set('fct_quant', 'r001', 'confidence', '1.0', basis='一手表格 / 目标口径前瞻 0.9')
    m.set('fct_quant', 'r003', 'confidence', '1.0', basis='一手表格 / 目标口径前瞻 0.9')
    m.set('fct_quant', 'r004', 'confidence', '1.0', basis='一手表格 / 目标口径前瞻 0.9')
    m.set('fct_quant', 'r008', 'confidence', '0.9', basis='一手表格 / 目标口径前瞻 0.9')
    m.set('fct_quant', 'r002', 'revision_flag', 'initial', basis='Q1 给出、Q2 重申，未修订')
    m.set('fct_quant', 'r201', 'snapshot_id', 'snap_nebius_shl_q2_2026', basis='快照')
    m.set('fct_quant', 'r201', 'period_start', '2026-04-01', basis='期间解析')
    m.set('fct_quant', 'r201', 'period_end', '2026-06-30', basis='期间解析')
    m.set('fct_quant', 'r201', 'confidence', '1.0', basis='一手')
    m.set('fct_quant', 'r202', 'snapshot_id', 'snap_nebius_shl_q2_2026', basis='快照')
    m.set('fct_quant', 'r202', 'period_start', '2026-04-01', basis='期间解析')
    m.set('fct_quant', 'r202', 'period_end', '2026-06-30', basis='期间解析')
    m.set('fct_quant', 'r202', 'confidence', '1.0', basis='一手')
    m.set('fct_quant', 'r204', 'snapshot_id', 'snap_nebius_shl_q2_2026', basis='快照')
    m.set('fct_quant', 'r204', 'period_start', '2026-04-01', basis='期间解析')
    m.set('fct_quant', 'r204', 'period_end', '2026-06-30', basis='期间解析')
    m.set('fct_quant', 'r204', 'confidence', '1.0', basis='一手')
    m.set('fct_quant', 'r205', 'snapshot_id', 'snap_nebius_shl_q2_2026', basis='快照')
    m.set('fct_quant', 'r205', 'period_start', '2026-06-30', basis='期间解析')
    m.set('fct_quant', 'r205', 'period_end', '2026-06-30', basis='期间解析')
    m.set('fct_quant', 'r205', 'confidence', '1.0', basis='一手')
    m.set('fct_event', 'r210', 'snapshot_id', 'snap_nebius_shl_q2_2026', basis='快照')
    m.set('fct_event', 'r210', 'confidence', '1.0', basis='一手')
    m.set('fct_quant', 'r213', 'snapshot_id', 'snap_nebius_shl_q1_2026', basis='快照')
    m.set('fct_quant', 'r213', 'period_start', '2026-01-01', basis='期间解析')
    m.set('fct_quant', 'r213', 'period_end', '2026-03-31', basis='期间解析')
    m.set('fct_quant', 'r213', 'confidence', '1.0', basis='一手')
    m.set('fct_quant', 'r214', 'snapshot_id', 'snap_nebius_shl_q1_2026', basis='快照')
    m.set('fct_quant', 'r214', 'period_start', '2026-01-01', basis='期间解析')
    m.set('fct_quant', 'r214', 'period_end', '2026-03-31', basis='期间解析')
    m.set('fct_quant', 'r214', 'confidence', '1.0', basis='一手')
    m.set('fct_quant', 'r215', 'snapshot_id', 'snap_nebius_shl_q1_2026', basis='快照')
    m.set('fct_quant', 'r215', 'period_start', '2026-03-31', basis='期间解析')
    m.set('fct_quant', 'r215', 'period_end', '2026-03-31', basis='期间解析')
    m.set('fct_quant', 'r215', 'confidence', '1.0', basis='一手')
    m.set('fct_quant', 'r216', 'snapshot_id', 'snap_nebius_shl_q1_2026', basis='快照')
    m.set('fct_quant', 'r216', 'period_start', '2026-01-01', basis='期间解析')
    m.set('fct_quant', 'r216', 'period_end', '2026-03-31', basis='期间解析')
    m.set('fct_quant', 'r216', 'confidence', '1.0', basis='一手')
    m.set('fct_quant', 'r217', 'snapshot_id', 'snap_nebius_shl_q1_2026', basis='快照')
    m.set('fct_quant', 'r217', 'period_start', '2026-01-01', basis='期间解析')
    m.set('fct_quant', 'r217', 'period_end', '2026-03-31', basis='期间解析')
    m.set('fct_quant', 'r217', 'confidence', '1.0', basis='一手')
    m.set('fct_quant', 'r218', 'snapshot_id', 'snap_nebius_shl_q1_2026', basis='快照')
    m.set('fct_quant', 'r218', 'period_start', '2026-12-31', basis='期间解析')
    m.set('fct_quant', 'r218', 'period_end', '2026-12-31', basis='期间解析')
    m.set('fct_quant', 'r218', 'confidence', '1.0', basis='一手')
    m.set('fct_quant', 'r001', 'qoq', '0.4594', basis='582.3 / 399.0 − 1')
    m.set('fct_quant', 'r201', 'qoq', '0.4755', basis='575 / 389.7 − 1')
    m.set('fct_quant', 'r004', 'qoq', '0.5625', basis='3.0 / 1.92 − 1')
    m.set('fct_quant', 'r003', 'qoq', '0.8239', basis='236.2 / 129.5 − 1')
    m.set('fct_quant', 'r204', 'qoq', '1.28', basis='5.7 / 2.5 − 1')
    # ---- fct_event（29 个字段）----
    m.set('fct_event', 'r006', 'event_type', 'contract', basis='客户承诺')
    m.set('fct_event', 'r006', 'amount', '40', basis='>$40B 取下限')
    m.set('fct_event', 'r006', 'currency', 'USD', basis='—')
    m.set('fct_event', 'r006', 'relation', 'customer_commitments', basis='—')
    m.set('fct_event', 'r006', 'snapshot_id', 'snap_nebius_shl_q2_2026', basis='快照')
    m.set('fct_event', 'r007', 'event_type', 'contract', basis='客户预付指引')
    m.set('fct_event', 'r007', 'amount', '9', basis='>$9B 取下限')
    m.set('fct_event', 'r007', 'currency', 'USD', basis='—')
    m.set('fct_event', 'r007', 'amount_type', 'annualized', basis='2026 全年')
    m.set('fct_event', 'r007', 'snapshot_id', 'snap_nebius_shl_q2_2026', basis='快照')
    m.set('fct_event', 'r009', 'event_type', 'launch', basis='并网电力目标')
    m.set('fct_event', 'r009', 'snapshot_id', 'snap_nebius_shl_q1_2026', basis='快照')
    m.set('fct_event', 'r009', 'event_date', '2026-12-31', basis='年底目标')
    m.set('fct_event', 'r206', 'snapshot_id', 'snap_nebius_shl_q2_2026', basis='快照')
    m.set('fct_event', 'r207', 'snapshot_id', 'snap_nebius_shl_q2_2026', basis='快照')
    m.set('fct_event', 'r209', 'snapshot_id', 'snap_nebius_shl_q2_2026', basis='快照')
    m.set('fct_event', 'r211', 'snapshot_id', 'snap_nebius_shl_q2_2026', basis='快照')
    m.set('fct_event', 'r212', 'snapshot_id', 'snap_nebius_shl_q2_2026', basis='快照')
    m.set('fct_event', 'r206', 'event_type', 'funding', basis='担保债融资')
    m.set('fct_event', 'r206', 'amount', '775', basis='—')
    m.set('fct_event', 'r206', 'currency', 'USD', basis='—')
    m.set('fct_event', 'r206', 'amount_type', 'one_time', basis='—')
    m.set('fct_event', 'r206', 'event_date', '2026-07-15', basis='7 月，日未披露，取月中')
    m.set('fct_event', 'r206', 'event_date_text', '2026-07', basis='原文 “In July”')
    m.set('fct_event', 'r207', 'relation', 'landmark_deals', basis='—')
    m.set('fct_event', 'r209', 'event_type', 'contract', basis='短期容量合同')
    m.set('fct_event', 'r211', 'event_type', 'launch', basis='站点扩张')
    m.set('fct_event', 'r212', 'event_type', 'other', basis='客户名单')
    m.set('fct_event', 'r212', 'relation', 'customer_list', basis='—')
    # ---- fct_opinion（52 个字段）----
    m.set('fct_opinion', 'r010', 'variable', 'ACV per MW', basis='codebook icl-v1')
    m.set('fct_opinion', 'r010', 'direction', 'up', basis='相对 thesis')
    m.set('fct_opinion', 'r010', 'strength', 'strong', basis='表述强度')
    m.set('fct_opinion', 'r010', 'level', '2', basis='1 提及 / 2 量化 / 3 承诺')
    m.set('fct_opinion', 'r010', 'codebook_version', 'icl-codebook-v1', basis='doc22')
    m.set('fct_opinion', 'r010', 'speaker', 'Nebius 管理层（股东信 / 电话会）', basis='SHL')
    m.set('fct_opinion', 'r010', 'snapshot_id', 'snap_nebius_shl_q2_2026', basis='快照')
    m.set('fct_opinion', 'r011', 'variable', '新一代 GPU 定价机会', basis='codebook icl-v1')
    m.set('fct_opinion', 'r011', 'direction', 'up', basis='相对 thesis')
    m.set('fct_opinion', 'r011', 'strength', 'strong', basis='表述强度')
    m.set('fct_opinion', 'r011', 'level', '2', basis='1 提及 / 2 量化 / 3 承诺')
    m.set('fct_opinion', 'r011', 'codebook_version', 'icl-codebook-v1', basis='doc22')
    m.set('fct_opinion', 'r011', 'speaker', 'Nebius 管理层（股东信 / 电话会）', basis='SHL')
    m.set('fct_opinion', 'r011', 'snapshot_id', 'snap_nebius_shl_q2_2026', basis='快照')
    m.set('fct_opinion', 'r012', 'variable', 'FY2026 capex 指引', basis='codebook icl-v1')
    m.set('fct_opinion', 'r012', 'direction', 'flat', basis='相对 thesis')
    m.set('fct_opinion', 'r012', 'strength', 'medium', basis='表述强度')
    m.set('fct_opinion', 'r012', 'level', '1', basis='1 提及 / 2 量化 / 3 承诺')
    m.set('fct_opinion', 'r012', 'codebook_version', 'icl-codebook-v1', basis='doc22')
    m.set('fct_opinion', 'r012', 'speaker', 'Nebius 管理层（股东信 / 电话会）', basis='SHL')
    m.set('fct_opinion', 'r012', 'snapshot_id', 'snap_nebius_shl_q2_2026', basis='快照')
    m.set('fct_opinion', 'r014', 'variable', '对账 regime', basis='codebook icl-v1')
    m.set('fct_opinion', 'r014', 'direction', 'up', basis='相对 thesis')
    m.set('fct_opinion', 'r014', 'strength', 'medium', basis='表述强度')
    m.set('fct_opinion', 'r014', 'level', '2', basis='1 提及 / 2 量化 / 3 承诺')
    m.set('fct_opinion', 'r014', 'codebook_version', 'icl-codebook-v1', basis='doc22')
    m.set('fct_opinion', 'r014', 'speaker', 'Nebius 管理层（股东信 / 电话会）', basis='SHL')
    m.set('fct_opinion', 'r014', 'snapshot_id', 'snap_nebius_shl_q2_2026', basis='快照')
    m.set('fct_opinion', 'r014', 'speaker', '对账规则（C）+ 裁量（D）', basis='doc22 §五')
    m.set('fct_opinion', 'r014', 'speaker_role', '', basis='非管理层')
    m.set('fct_opinion', 'r014', 'owner', 'D', basis='裁量', owner='D')
    m.set('fct_opinion', 'r203', 'snapshot_id', 'snap_nebius_shl_q2_2026', basis='快照')
    m.set('fct_opinion', 'r208', 'snapshot_id', 'snap_nebius_shl_q2_2026', basis='快照')
    m.set('fct_opinion', 'r203', 'variable', 'AI cloud Adj. EBITDA 利润率', basis='codebook icl-v1')
    m.set('fct_opinion', 'r203', 'direction', 'up', basis='相对 thesis')
    m.set('fct_opinion', 'r203', 'strength', 'strong', basis='—')
    m.set('fct_opinion', 'r203', 'level', '2', basis='—')
    m.set('fct_opinion', 'r203', 'codebook_version', 'icl-codebook-v1', basis='doc22')
    m.set('fct_opinion', 'r203', 'speaker', 'Nebius 管理层（股东信）', basis='SHL')
    m.set('fct_opinion', 'r203', 'speaker_role', 'management', basis='—')
    m.set('fct_opinion', 'r208', 'variable', '老一代 GPU 定价 vs Q1', basis='codebook icl-v1')
    m.set('fct_opinion', 'r208', 'direction', 'up', basis='相对 thesis')
    m.set('fct_opinion', 'r208', 'strength', 'strong', basis='—')
    m.set('fct_opinion', 'r208', 'level', '2', basis='—')
    m.set('fct_opinion', 'r208', 'codebook_version', 'icl-codebook-v1', basis='doc22')
    m.set('fct_opinion', 'r208', 'speaker', 'Nebius 管理层（股东信）', basis='SHL')
    m.set('fct_opinion', 'r208', 'speaker_role', 'management', basis='—')
    # ---- edge_registry（62 个字段）----
    m.set('edge_registry', 'e_optics_nbis', 'mechanism', '中际旭创 800G/1.6T 出货 ≈ 全球 AI 集群在建强度 → neocloud 扩张环境 → NBIS 产能骑乘（赛道 beta）', basis='doc25 §1.2 / 本轮')
    m.set('edge_registry', 'e_optics_nbis', 'owner', 'B', basis='分工')
    m.set('edge_registry', 'e_optics_nbis', 'last_validated', '2026-09-20', basis='本轮')
    m.set('edge_registry', 'e_eoptolink_nbis', 'mechanism', '新易盛出货同理，1.6T / Google 敞口更高', basis='doc25 §1.2 / 本轮')
    m.set('edge_registry', 'e_eoptolink_nbis', 'owner', 'B', basis='分工')
    m.set('edge_registry', 'e_eoptolink_nbis', 'last_validated', '2026-09-20', basis='本轮')
    m.set('edge_registry', 'e_power_nbis', 'mechanism', '自有 / 合同电力上电 → 产能兑现 → 收入确认；延期 = 收入递延', basis='doc25 §1.2 / 本轮')
    m.set('edge_registry', 'e_power_nbis', 'owner', 'B', basis='分工')
    m.set('edge_registry', 'e_power_nbis', 'last_validated', '2026-09-20', basis='本轮')
    m.set('edge_registry', 'e_backlog_nbis', 'mechanism', '本体：客户承诺与预付即 NBIS 自身，基准非信号', basis='doc25 §1.2 / 本轮')
    m.set('edge_registry', 'e_backlog_nbis', 'owner', 'A', basis='分工')
    m.set('edge_registry', 'e_backlog_nbis', 'last_validated', '2026-09-20', basis='本轮')
    m.set('edge_registry', 'e_labfund_nbis', 'mechanism', 'lab 拿到融资 → 有算力采购力 → 与 NBIS 签约；Reflection 2025-10 融 $2B → 2026-07 签 $1B 合同证过一次', basis='doc25 §1.2 / 本轮')
    m.set('edge_registry', 'e_labfund_nbis', 'owner', 'B', basis='分工')
    m.set('edge_registry', 'e_labfund_nbis', 'last_validated', '2026-09-20', basis='本轮')
    m.set('edge_registry', 'e_labfund_nbis', 'cert_score', '0.5', basis='单样本真值对账，定性 0.5')
    m.set('edge_registry', 'e_labfund_nbis', 'lead_measured', '278d（Reflection 一例）', basis='事件间隔实测')
    m.set('edge_registry', 'e_frontierfund_nbis', 'mechanism', '前沿 lab 融资总量 → neocloud 需求；非确认客户，只给方向', basis='doc25 §1.2 / 本轮')
    m.set('edge_registry', 'e_frontierfund_nbis', 'owner', 'B', basis='分工')
    m.set('edge_registry', 'e_frontierfund_nbis', 'last_validated', '2026-09-20', basis='本轮')
    m.set('edge_registry', 'e_capability_nbis', 'mechanism', '模型能力 / 训练算力增速 → 推理训练需求 → lab 采购 → NBIS 用量；3 跳只方向', basis='doc25 §1.2 / 本轮')
    m.set('edge_registry', 'e_capability_nbis', 'owner', 'B', basis='分工')
    m.set('edge_registry', 'e_capability_nbis', 'last_validated', '2026-09-20', basis='本轮')
    m.set('edge_registry', 'e_token_nbis', 'mechanism', '推理用量 → 推理需求 → neocloud 用量；OpenRouter 只是一角', basis='doc25 §1.2 / 本轮')
    m.set('edge_registry', 'e_token_nbis', 'owner', 'B', basis='分工')
    m.set('edge_registry', 'e_token_nbis', 'last_validated', '2026-09-20', basis='本轮')
    m.set('edge_registry', 'e_costtoken_nbis', 'mechanism', 'cost/token 变化 → 推理需求弹性 → neocloud 用量；分档（C16′）', basis='doc25 §1.2 / 本轮')
    m.set('edge_registry', 'e_costtoken_nbis', 'owner', 'B', basis='分工')
    m.set('edge_registry', 'e_costtoken_nbis', 'last_validated', '2026-09-20', basis='本轮')
    m.set('edge_registry', 'e_export_nbis', 'mechanism', 'BIS 许可 / 232 关税 → NVIDIA 中国收入与供给 → GPU 可得与成本 → NBIS；NVDA 指引不含中国 DC 为「未兑现」证据', basis='doc25 §1.2 / 本轮')
    m.set('edge_registry', 'e_export_nbis', 'owner', 'D', basis='分工')
    m.set('edge_registry', 'e_export_nbis', 'last_validated', '2026-09-20', basis='本轮')
    m.set('edge_registry', 'e_power_reg_nbis', 'mechanism', '数据中心用电总量与审批 → 上电节奏 → NBIS 并网', basis='doc25 §1.2 / 本轮')
    m.set('edge_registry', 'e_power_reg_nbis', 'owner', 'B', basis='分工')
    m.set('edge_registry', 'e_power_reg_nbis', 'last_validated', '2026-09-20', basis='本轮')
    m.set('edge_registry', 'e_circular_nbis', 'mechanism', '供芯方 NVIDIA 入股 $2B，同时是客户 Reflection 领投方 → 采购与融资条件相互依赖；「循环」判读 D', basis='doc25 §1.2 / 本轮')
    m.set('edge_registry', 'e_circular_nbis', 'owner', 'D', basis='分工')
    m.set('edge_registry', 'e_circular_nbis', 'last_validated', '2026-09-20', basis='本轮')
    m.set('edge_registry', 'e_crwv_nbis', 'mechanism', '同业 read-through：CRWV backlog / capex / 收入与 NBIS 同向；两者均上市可回归', basis='doc25 §1.2 / 本轮')
    m.set('edge_registry', 'e_crwv_nbis', 'owner', 'B', basis='分工')
    m.set('edge_registry', 'e_crwv_nbis', 'last_validated', '2026-09-20', basis='本轮')
    m.set('edge_registry', 'e_gpu_nbis', 'mechanism', 'NVDA 数据中心出货 / 代际 → NBIS 采购成本与可得', basis='doc25 §1.2 / 本轮')
    m.set('edge_registry', 'e_gpu_nbis', 'owner', 'B', basis='分工')
    m.set('edge_registry', 'e_gpu_nbis', 'last_validated', '2026-09-20', basis='本轮')
    m.set('edge_registry', 'e_capex_nbis', 'mechanism', '四家 hyperscaler capex → 全球 AI 在建强度 → neocloud 扩张环境（下游代理 C4）', basis='doc25 §1.2 / 本轮')
    m.set('edge_registry', 'e_capex_nbis', 'owner', 'B', basis='分工')
    m.set('edge_registry', 'e_capex_nbis', 'last_validated', '2026-09-20', basis='本轮')
    m.set('edge_registry', 'e_backlog_nbis', 'evidence_ids', '["r006", "r007", "r204", "r205", "r206", "r207", "r212"]', basis='由库生成：from_metric（含显式关联指标）的全部记录', owner='A')
    m.set('edge_registry', 'e_power_nbis', 'evidence_ids', '["r008", "r009", "r209", "r210", "r211"]', basis='由库生成：from_metric（含显式关联指标）的全部记录', owner='A')
    m.set('edge_registry', 'e_optics_nbis', 'evidence_ids', '["r078", "r079", "r080", "r081", "r082"]', basis='由库生成：from_metric（含显式关联指标）的全部记录', owner='A')
    m.set('edge_registry', 'e_labfund_nbis', 'evidence_ids', '["r115", "r116", "r117"]', basis='由库生成：from_metric（含显式关联指标）的全部记录', owner='A')
    m.set('edge_registry', 'e_capability_nbis', 'evidence_ids', '["r142", "r143"]', basis='由库生成：from_metric（含显式关联指标）的全部记录', owner='A')
    m.set('edge_registry', 'e_token_nbis', 'evidence_ids', '["r162", "r163"]', basis='由库生成：from_metric（含显式关联指标）的全部记录', owner='A')
    m.set('edge_registry', 'e_export_nbis', 'evidence_ids', '["r165", "r166", "r167"]', basis='由库生成：from_metric（含显式关联指标）的全部记录', owner='A')
    m.set('edge_registry', 'e_power_reg_nbis', 'evidence_ids', '["r105", "r106"]', basis='由库生成：from_metric（含显式关联指标）的全部记录', owner='A')
    m.set('edge_registry', 'e_frontierfund_nbis', 'evidence_ids', '["r121", "r122", "r123", "r124", "r125"]', basis='由库生成：from_metric（含显式关联指标）的全部记录', owner='A')
    m.set('edge_registry', 'e_circular_nbis', 'evidence_ids', '["r128"]', basis='由库生成：from_metric（含显式关联指标）的全部记录', owner='A')
    m.set('edge_registry', 'e_crwv_nbis', 'evidence_ids', '["r134", "r135", "r136", "r137", "r138", "r139"]', basis='由库生成：from_metric（含显式关联指标）的全部记录', owner='A')
    m.set('edge_registry', 'e_gpu_nbis', 'evidence_ids', '["r091", "r092"]', basis='由库生成：from_metric（含显式关联指标）的全部记录', owner='A')
    m.set('edge_registry', 'e_costtoken_nbis', 'evidence_ids', '["r156", "r157", "r158", "r159", "r160", "r161"]', basis='由库生成：from_metric（含显式关联指标）的全部记录', owner='A')
    m.set('edge_registry', 'e_capex_nbis', 'evidence_ids', '["r093", "r094", "r095", "r096", "r097", "r098", "r099", "r100", "r101", "r102", "r103", "r104"]', basis='由库生成：from_metric（含显式关联指标）的全部记录', owner='A')
    m.set('edge_registry', 'e_eoptolink_nbis', 'evidence_ids', '["r083", "r084", "r085", "r086"]', basis='由库生成：from_metric（含显式关联指标）的全部记录', owner='A')
    # ---- source_master（15 个字段）----
    m.set('source_master', 'src_nebius_6_k_ex_99_1', 'publisher', 'Nebius Group N.V. via SEC EDGAR', basis='来源页')
    m.set('source_master', 'src_nebius_6_k_ex_99_1', 'frequency', '季', basis='—')
    m.set('source_master', 'src_nebius_6_k_ex_99_1', 'reliability_note', '一手交易所备案，数字精确到 0.1M', basis='—')
    m.set('source_master', 'src_nebius_q2_2026_shareholder_letter', 'publisher', 'Nebius Group IR', basis='来源页')
    m.set('source_master', 'src_nebius_q2_2026_shareholder_letter', 'frequency', '季', basis='—')
    m.set('source_master', 'src_nebius_q2_2026_shareholder_letter', 'reliability_note', '一手 IR 文件；含 ARR 定义与非 GAAP 调节；本地快照 snap_nebius_shl_q2_2026', basis='—')
    m.set('source_master', 'src_nebius_q1_2026_shareholder_letter', 'publisher', 'Nebius Group IR', basis='来源页')
    m.set('source_master', 'src_nebius_q1_2026_shareholder_letter', 'frequency', '季', basis='—')
    m.set('source_master', 'src_nebius_q1_2026_shareholder_letter', 'reliability_note', '一手；并网电力 800MW–1GW 出处；快照 snap_nebius_shl_q1_2026', basis='—')
    m.set('source_master', 'src_nbis_q2_电话会_transcript_the_globe_and_mail_转载', 'publisher', 'The Globe and Mail（转载 Motley Fool transcript）', basis='来源页')
    m.set('source_master', 'src_nbis_q2_电话会_transcript_the_globe_and_mail_转载', 'frequency', '季', basis='—')
    m.set('source_master', 'src_nbis_q2_电话会_transcript_the_globe_and_mail_转载', 'reliability_note', '转载 transcript，P2；官方 transcript 待钉', basis='—')
    m.set('source_master', 'src_nebius_newsroom', 'publisher', 'Nebius Group newsroom', basis='来源页')
    m.set('source_master', 'src_nebius_newsroom', 'frequency', '事件', basis='—')
    m.set('source_master', 'src_nebius_newsroom', 'reliability_note', '一手新闻稿', basis='—')
