# -*- coding: utf-8 -*-
"""0006 · 思路层入库：按题面四块组织（破题 / 分析角度 / 数据 / 结果展现）→ 关键决策分叉（只记熵减点）→ 落地产物（双向锚定到表 / 列 / 视图 / 规则 / 假设）· owner B · 2026-09-20
四块对应题面：① 我怎么破题 ② 自定的分析角度 ③ 数据来源与更新频率与 schema ④ 结果展现方式。内容从 doc31 / 17-思维链续 / 13-思路总梳理 / 14-协作日志起草，B 初稿，D 复核。
组织原则：主线 4 块（对齐题面，不按数据处理层）；分叉只保留有取舍的决策（weight=core 面试主讲，detail 演示模式折叠）；每个决策锚到库里的产物，v_column_origin 反查。"""
import json
OWNER = 'B'
def J(*xs): return json.dumps(list(xs), ensure_ascii=False)

NODES = [
  ('N1', 1, '破题：怎么理解「监测 AI 发展的追踪体系」', '这道题在问什么？这套体系给谁用、做到什么程度算答对？', '不是通用 AI 新闻跟踪；放在 Anatole 自下而上语境里要服务基金决策。监测对象是 AI 发展整体（能力前沿义 + 产业变现义），NBIS 只是验证点不是监测对象。打法：广度做骨架、深度做样板，先押 NBIS 钻穿再把方法平移。', '环 0 / 1 / 3', 'doc14 A1–A2 · doc24 扣题视图 · doc31'),
  ('N2', 2, '分析角度：怎么拆 AI 发展、映射到持仓、验证传导', '从什么角度分析 AI 发展？它的信号凭什么、怎么落到基金的持仓票上？', '供给侧七维 D1–D7（每维一条拆解主轴 complete-by-construction）；实体两轴 layer L1–L6 × maturity。映射从持仓票向上游反推（AI 发展→ticker，非 VC→ticker）；六类边 × 跳数，V = f(传导, 节点质量五因子 r/e/l/s/φ)，出可交易度 / 预警度双产出。每条边过三层确定性验证 T1/T2/T3；系数全登记为假设，只排序、未验证不下注。', '环 4 / 5 / 6 / 8 / 10', 'doc25 · doc21 §六 · doc24v2 / 26 · doc30 · E39 / E41'),
  ('N3', 3, '数据：来源、更新频率与 schema', '数据从哪来、多久更新一次、用什么 schema 存才严谨可溯源？', '四类数据（量价 / 事件 / 观点 / 前沿）各自 schema + 通用元数据层。真数不用示例值，P1–P5 溯源 + 本地快照 + 原文锚点；口径不对降级钉一手。更新频率按指标天然频率，下次发布用四级依据标注。schema 设计先于数据完整落库，库为真源、改库走 migrations + 字段级 change_log；NBIS 跑穿再平移。', '环 2 / 9 / 13', 'doc17 · doc23 · doc28 · doc33 · doc21 §〇 · E40 / E43 / E44'),
  ('N4', 4, '结果展现方式：面板构建思路', '结果给谁看、用什么形态呈现、面板上放什么？', '面板服务研究员与 PM 不是数据岗。主视图日历式（Actual / Forecast / Prior），映射用蝴蝶结按需。列按决策时刻定（链状态 / 本周动了什么 / 预警 / 领先读），不是活动量与日程；关键事实作者写；下钻整页按信号角色分模板，术语三层分离。', '环 7 / 12 / 14–20', 'doc17 · E27–E28 · E35–E38 · E42 · E45'),
]
FORKS = [  # node, seq, question, options, chosen, rationale, before_after, weight, log_ref
  ('N1', 1, '做什么样的体系', J('通用美股 AI 新闻 / 大盘追踪', '基金语境的 demand-anchored 体系'), '基金语境的 demand-anchored 体系', '岗位内核是用地面数据 nowcast 持仓 KPI（Falcon Edge 打法、FF 教训）；锚了持仓才有验证点、能对账。', '全面铺新闻 → 锚持仓、服务决策', 'core', '环 0 / 1'),
  ('N1', 2, '广度还是深度', J('平铺覆盖全部持仓', '先押 NBIS 钻深度，方法论平移'), '先押 NBIS 钻深度，方法论平移', '有限时间投在「链稳不稳」上，不在铺面；样板跑穿后其余票复用。', '倾向平铺 → 广度骨架 + 深度样板', 'core', '环 1'),
  ('N1', 3, '扣题自检', J('做着做着变成给 NBIS 选股', '能力前沿义与产业变现义端平，NBIS 只是验证点'), '能力前沿义与产业变现义端平，NBIS 只是验证点', '题目是监测 AI 发展；「能力前沿义做薄 = 像选股」是显式判断出来的风险，为 N2 / N3 重构埋线。', '指标偏向持仓相关产业读数 → doc24 扣题视图', 'core', '环 3'),
  ('N1', 4, '协作方式', J('一股脑铺全部内容', 'append-only 协作日志 + 三层可读性 L0 / L1 / L2'), 'append-only 协作日志 + 三层可读性 L0 / L1 / L2', '全面性会淹没重点；证据 / 审计 / 呈现分层。', '全面但可读性差 → doc14 契约', 'detail', '环 0'),
  ('N2', 1, 'scope 几维', J('五维', '七维 D1–D7（专家视角查全 / 查准 / 查重 / 排序）'), '七维 D1–D7（专家视角查全 / 查准 / 查重 / 排序）', '五维有缺口（数据 / 算法 / 政策）与重合（推理 / 资本）；推理拆 D5 方法 vs D6 用量，资本归 D3。', '5 维 → 7 维 + 每维拆解主轴 + 双排序', 'core', '环 5 · doc26'),
  ('N2', 2, '实体的轴', J('early_A 当一层', 'layer L1–L6 × maturity 两轴正交'), 'layer L1–L6 × maturity 两轴正交', 'early_A 不属于 L1–L6；早期性是成熟度维度，不是价值栈的一层。', 'early_A 混在 layer 里 → 拆两轴', 'core', '环 10 ①'),
  ('N2', 3, '早期信号三子流', J('作字段 signal_stream', '作视图 v_early_signal'), '作视图 v_early_signal', '可由 maturity × data_class 推导，字段会与视图重合；由此立下建模原则「可推导的一律作视图」。', '留了 signal_stream 字段 → 删字段改视图 + §〇 原则', 'core', '环 10 ① · E24'),
  ('N2', 4, '中国侧的位置', J('中国侧 / 可回测为主判据', '附加标签，主判据 = 是否映射到票 × 票分量 × 杠杆'), '附加标签，主判据 = 是否映射到票 × 票分量 × 杠杆', '中国侧是独家性来源，不是入选门槛；否则 scope 会被数据可得性绑架。', '判据以中国侧为重 → 降为标签', 'detail', '环 4 · E19'),
  ('N2', 5, '前沿类怎么放', J('挂到票上', 'topic-driven 独立雷达，源分层分级'), 'topic-driven 独立雷达，源分层分级', '前沿知识流多跳只给方向，硬挂票会假映射；两道闸（立场 / 可验证性）先过再松映射。', '前沿混在指标里 → doc29 雷达', 'detail', 'doc29'),
  ('N2', 6, '映射主线', J('VC data → ticker 传导为骨架', 'AI 发展 → ticker 映射范式，VC 仅参考'), 'AI 发展 → ticker 映射范式，VC 仅参考', '参考路线不是我们的主线；要的是分析清楚 AI 发展到基金标的这条链的思考逻辑与范式。全程最大一次方向纠偏。', 'VC→ticker → AI→ticker', 'core', '环 4'),
  ('N2', 7, '映射方向', J('从上游赛道往下找票', '从持仓票向上游反推节点'), '从持仓票向上游反推节点', '有票才有分量与杠杆，映射才可验证；先 scope 后映射。', '上游找票 → 票向上游', 'core', '环 4 · doc25'),
  ('N2', 8, 'value 的构成', J('只含传导（跳数 / 确定性）', '传导 × 节点质量五因子 r/e/l/s/φ'), '传导 × 节点质量五因子 r/e/l/s/φ', '同样的传导，节点的可靠性 / 独家性 / 领先性 / 信噪 / 频率不同，value 必须写进公式。', 'value 缺节点质量 → 补五因子', 'core', '环 6 ②'),
  ('N2', 9, '边的产出', J('单一分数', '可交易度 tradable 与预警度 warning 双产出'), '可交易度 tradable 与预警度 warning 双产出', '一条边对下注和对风险的用处不同，合成一个数会互相抵消；tradable = c·r·s·φ，warning = τ·l·e。', '单分 → 双产出 + 按票归一权重', 'core', 'doc25 · doc21 §六'),
  ('N2', 10, '跳数怎么定', J('直觉标', '定义 = 从票的利润因子沿因果链上溯到 AI 节点跨过的箭头数，逐票链式图'), '定义 = 从票的利润因子沿因果链上溯到 AI 节点跨过的箭头数，逐票链式图', '「跳数你是怎么规定的，依据列出来」；chain 列记中间节点，校验 hops = 中间节点 + 1。', '无定义 → 定义 + 链式图 + 校验', 'detail', '环 6 ①'),
  ('N2', 11, '边成立到什么程度', J('画出来默认成立', '只标方向', '三层验证 T1 可回测 / T2 结构成立 + 对账 / T3 方向级', '全部回归'), '三层验证 T1 可回测 / T2 结构成立 + 对账 / T3 方向级', '多数边两端没有可对齐的时序，硬回归是假精度；但可回测的（光模块 → NBIS）必须真回测。T3 不下注。', '默认成立 → edge_registry 三层 + 双真源 R+E', 'core', '环 8'),
  ('N2', 12, '系数是什么', J('当定值用', '登记为假设，只用于排序，绝对值待回测'), '登记为假设，只用于排序，绝对值待回测', '「系数你是怎么定的？如果是假设就要标出来」；状态机 assumption → calibrating → validated → retired，未验证🟠禁进阈值与仓位。', '系数当定值 → doc30 假设台账', 'core', '环 10 ②'),
  ('N2', 13, '算分以谁为准', J('手写分为准', '规则算分为准', '两者对账，分歧摆出来交 D'), '两者对账，分歧摆出来交 D', '对账暴露 7 条边分歧：规则把本体指标 l / φ 一律给 L，与 doc25 对「NBIS 电力上电 = 关键可观测量」的判断冲突 —— 因子必须逐条复核，规则只是起点。', '只有手写分 → v_edge_calc 对账 + reconcile_flag', 'core', 'E39'),
  ('N2', 14, '证据怎么挂', J('手填 evidence_ids', '由库按上游指标生成 + 校验'), '由库按上游指标生成 + 校验', '手填的一半指错记录；证据必须属于该边的上游指标，快照文件必须存在 —— 链断了要能第一时间发现。', '手填 → 库生成 + 两条校验', 'core', 'E41'),
  ('N3', 1, '数据怎么分', J('一张大表', '四类各自 schema + 通用元数据层'), '四类各自 schema + 通用元数据层', '数据的结构决定载体、频率、分工、呈现；类 1 可回归、类 2 可建图、类 3 codebook、类 4 聚类。', '—', 'core', 'doc17'),
  ('N3', 2, '二手数怎么用', J('转述先用着', '降级 P2 / P3 并回一手，钉 transcript / 原文'), '降级 P2 / P3 并回一手，钉 transcript / 原文', 'NBIS ARR / backlog 实为电话会口径，不是财报口径；诚实降级比看起来对更重要。', '当财报口径 → 降 P2、复验队列', 'core', '环 2'),
  ('N3', 3, '更新频率怎么定', J('全库统一定时刷新', '按指标天然频率 + 下次发布依据分级'), '按指标天然频率 + 下次发布依据分级', '不同数据频率天然不同：财报季度、供应链月度、政策与融资事件驱动、前沿榜单周更；下次发布用「公司公告 / 规则推定 / 估计 / 待定」四级依据标注，估的不当钉死的；knowledge_time 按原文粒度决定能否进时序。', '统一定时刷 → 按指标频率 + next_release 依据分级', 'core', 'doc17 · 日历排期'),
  ('N3', 4, '列什么时候建', J('有值才建列', '设计先于数据：doc21 全列落地，有值率是进度'), '设计先于数据：doc21 全列落地，有值率是进度', 'schema 是设计思路的载体；不落地的设计等于没有。', '压扁版 → schema v2 24 表 + 字典 / 关系 / 规则入库', 'core', 'E40'),
  ('N3', 5, '真源在哪', J('CSV 真源 + 全量重灌，库是缓存', '库真源 + 改库脚本 + 字段级改库账'), '库真源 + 改库脚本 + 字段级改库账', '补丁 CSV 让 UPDATE 0 行静默通过（抓到 17 行写错表）；basis 在 CSV 里库查不到；库为真源后从零重放 = 增量应用。', 'enrich/*.csv → migrations/ + change_log', 'core', 'E43'),
  ('N3', 6, 'schema 怎么验证', J('空表结构交付', '用 NBIS 真数把 schema 跑穿'), '用 NBIS 真数把 schema 跑穿', '框架不落到真数都是空的：源可得性 × 质量四档、逐字段真值、边验证执行手册。', '空表 → doc28 全链路实跑', 'core', '环 9'),
  ('N3', 7, '查证结果怎么用', J('查证 agent 结果直接用', '我方二次抽核，措辞跟着原文走'), '我方二次抽核，措辞跟着原文走', 'agent 有截断与转述；抽核后做了测量级修正（合同电力 vs 并网、承诺 vs backlog、tariff vs 抽成）。', '—', 'core', '环 13'),
  ('N3', 8, '纠错怎么记', J('覆盖旧值', '新行 + superseded_by，旧行不删'), '新行 + superseded_by，旧行不删', '旧值是当时可知的事实，删了回测失真；视图默认隐藏被取代行。', '—', 'detail', 'doc23 §五'),
  ('N3', 9, '原文怎么留', J('只存 URL', '本地快照 + 原文锚点'), '本地快照 + 原文锚点', 'IR 站 403、页面会改；snapshot_id 指向文件，校验文件必须存在。', '—', 'detail', 'E41 / E44'),
  ('N3', 10, '时间轴用什么', J('用发布日 / 抓取日', 'knowledge_time 按原文粒度，不伪造精度'), 'knowledge_time 按原文粒度，不伪造精度', 'point-in-time 是回测生命线；月 → 15 日、季 / 年 → NULL 只供排序；as-of = max(knowledge_date)。', '—', 'detail', 'doc17 §2.1 · R14'),
  ('N3', 11, '文档怎么维护', J('手写', '从库生成（SCHEMA.md / 浏览器），字典完整性由校验保证'), '从库生成（SCHEMA.md / 浏览器），字典完整性由校验保证', '手写必漂移；库里每列必须有字典条目否则建库失败。', '—', 'detail', 'E40'),
  ('N3', 12, '数据库选型', J('DuckDB 单文件', 'Supabase / Postgres'), 'DuckDB 单文件（交付前）；之后 Supabase', '零依赖、评审者能开、可复现；doc21 本就是 Postgres DDL，迁移只改方言。', '—', 'detail', 'E45'),
  ('N4', 1, '主视图形态', J('K 线 / 节点图为主', '日历式为主（Actual / Forecast / Prior），蝴蝶结按需'), '日历式为主（Actual / Forecast / Prior），蝴蝶结按需', '监测的是事件流不是价格；按用户 - 场景 - 意图 - 信息 - 形式分析后图只在「看影响」时需要。', '节点图 → 日历 + 按需图', 'core', '环 12 / 15 · E27'),
  ('N4', 2, '面板给谁', J('数据岗', '研究员与 PM'), '研究员与 PM', '数据岗用库和校验就够；入口是研究员的，出口却是数据岗的 —— 这是定位错位。', '抽屉里全是 schema 信息 → 研究向 impact card', 'core', '环 16'),
  ('N4', 3, '信号列怎么定', J('活动量与日程（新观测数、下次几天）', '按决策时刻定列：链状态 / 本周动了什么 / 预警 / 领先读'), '按决策时刻定列：链状态 / 本周动了什么 / 预警 / 领先读', '研究员要状态与变化，不是计数与日期；五个决策时刻（持有 / 财报前 / 风险 / 证伪 / 轮动）各对一列。', '计数列 → 决策列 + 方向判断 A11', 'core', '环 19'),
  ('N4', 4, '呈现形态（图）', J('ASCII 链', 'HTML 距离梯图', '蝴蝶结（供给左 / 需求右，x = 跳数，颜色 = 产出，线型 = 确定性）'), '蝴蝶结（供给左 / 需求右，x = 跳数，颜色 = 产出，线型 = 确定性）', '从图论 / 信息论角度选型取决于标签维度数；一张图承载六个通道。', 'ASCII → 梯图 → 蝴蝶结', 'detail', '环 7'),
  ('N4', 5, '关键事实怎么来', J('模板拼字段', '作者写：前因 / 关键数据 / 相关方 / 后果 + 证伪条件'), '作者写：前因 / 关键数据 / 相关方 / 后果 + 证伪条件', '拼出来的是字段重复，不是事实；简报有 owner、有状态。', '—', 'detail', '环 18'),
  ('N4', 6, '下钻与术语', J('抽屉 + 内部词', '整页按角色分模板 + 术语三层（用户 / 分析 / 方法）'), '整页按角色分模板 + 术语三层（用户 / 分析 / 方法）', '不同数据类的决策逻辑不同，页面要 by case；使用者读不懂内部词是「肯定不行的」。', '—', 'detail', '环 18 / 20'),
  ('N4', 7, '思路放哪', J('只在 markdown', '思路层入库，与表 / 列双向锚定'), '思路层入库，与表 / 列双向锚定', '数据表看不到「为什么这么设计」就讲不清；按数据流分层是处理顺序不是思考顺序。', '按接入 / 资产 / 治理分层 → 按主线 / 分叉 / 产物', 'detail', 'E45'),
]
ANCHORS = [  # fork_id, kind, ref, how
  ('F1.1', 'column', 'metric_registry.entry', '持仓 / AI 两个入口：需求侧锚点与供给侧节点分开登记'),
  ('F1.1', 'table', 'fct_position', '13F 仓位是需求侧的事实锚'),
  ('F1.1', 'column', 'entity_master.in_book', '实体是否在书里'),
  ('F1.2', 'migration', '0001_nbis_round1', 'NBIS 先跑穿：第一轮逐字段填充'),
  ('F1.2', 'migration', '0003_rbrk_round1', '方法论平移到第二票'),
  ('F1.3', 'column', 'metric_registry.dim', '供给侧七维保证监测对象是 AI 发展整体'),
  ('F1.3', 'view', 'v_signal_latest', '视图 A 按 D1–D7 组织，不按票'),
  ('F1.4', 'file', '14-协作日志续.md', 'append-only 日志 E27–E45'),
  ('F2.1', 'column', 'metric_registry.dim', 'D1–D7'),
  ('F2.1', 'table', 'fct_frontier', '类 4 前沿主表'),
  ('F2.2', 'column', 'entity_master.layer', '价值栈 L1–L6'),
  ('F2.2', 'column', 'entity_master.maturity', '成熟度轴'),
  ('F2.3', 'view', 'v_early_signal', '早期信号层 = maturity ∈ {research, private} 的视图'),
  ('F2.3', 'column', 'schema_doc.served_by_view', '设计为字段但可推导者标视图'),
  ('F2.4', 'column', 'entity_master.country', '中国侧作标签'),
  ('F2.4', 'column', 'metric_factor.e', '独家性因子承接中国侧价值'),
  ('F2.5', 'column', 'fct_frontier.source_stance', '闸 1 立场'),
  ('F2.5', 'column', 'fct_frontier.verifiability', '闸 2 可验证性'),
  ('F2.5', 'column', 'fct_frontier.industry_impact', '过闸后再松映射'),
  ('F2.6', 'table', 'edge_registry', '真源 E：from_metric → to_ticker'),
  ('F2.6', 'column', 'edge_registry.edge_type', '六类边 E1–E6'),
  ('F2.7', 'column', 'edge_registry.to_ticker', '边的终点是票'),
  ('F2.7', 'column', 'edge_registry.side', 'supply / demand / regime / compete / self'),
  ('F2.7', 'column', 'entity_ticker_map.map_path', '补丁③ 映射路径'),
  ('F2.8', 'table', 'metric_factor', 'r / e / l / s / φ'),
  ('F2.8', 'rule', 'R1', 'valuable_score = w_e·e + w_s·s + w_r·r + w_phi·φ'),
  ('F2.8', 'view', 'v_metric_score', '节点分'),
  ('F2.9', 'rule', 'R5', 'tradable = c·r·s·φ'),
  ('F2.9', 'rule', 'R6', 'warning = τ·l·e'),
  ('F2.9', 'rule', 'R7', '按票归一权重'),
  ('F2.9', 'view', 'v_ticker_weight', '权重视图，weight_override 可覆盖'),
  ('F2.10', 'column', 'edge_registry.hops', '跳数'),
  ('F2.10', 'column', 'edge_registry.map_path', '中间节点链（doc18 补丁③ map_path，视图里叫 chain）'),
  ('F2.10', 'check', '2', 'hops = 中间节点数 + 1'),
  ('F4.4', 'view', 'v_ticker_map', '视图 B 持仓蝴蝶结'),
  ('F4.4', 'file', '16-AI发展监测日历.html', '蝴蝶结按需渲染'),
  ('F2.11', 'column', 'edge_registry.cert_tier', 'T1 / T2 / T3'),
  ('F2.11', 'column', 'edge_registry.cert_method', '验证方法'),
  ('F2.11', 'column', 'edge_registry.cert_score', '实测确定性（等回测）'),
  ('F2.11', 'column', 'edge_registry.lead_measured', '实测领先期'),
  ('F2.11', 'rule', 'R2', 'c = base_tier × decay^hops'),
  ('F2.11', 'rule', 'R3', 'τ 归一'),
  ('F2.12', 'table', 'assumption', '假设台账 A / B / C / R'),
  ('F2.12', 'table', 'coefficient', '系数表，视图只读这里'),
  ('F2.12', 'column', 'assumption.status', '状态机'),
  ('F2.12', 'column', 'metric_factor.status', 'draft 未复核不进阈值'),
  ('F2.12', 'table', 'observation_direction', 'A11 方向是判断不是数据'),
  ('F2.13', 'view', 'v_edge_calc', '规则算分与记录分对账'),
  ('F2.13', 'column', 'edge_registry.tradable_recorded', '手写 / 早期计算分'),
  ('F2.13', 'check', '7d', '打分对账 WARN'),
  ('F2.14', 'column', 'edge_registry.evidence_ids', '由库按上游指标生成'),
  ('F2.14', 'check', '7e', '证据必须属于上游指标'),
  ('F2.14', 'check', '7f', '快照文件必须存在'),
  ('F3.10', 'column', 'fct_quant.knowledge_time', '原文粒度'),
  ('F3.10', 'column', 'fct_quant.knowledge_date', '解析日期，不伪造精度'),
  ('F3.10', 'rule', 'R14', 'as-of = max(knowledge_date)'),
  ('F3.2', 'column', 'fct_quant.provenance', 'P1–P5'),
  ('F3.2', 'column', 'source_master.source_tier', '来源级别'),
  ('F3.2', 'view', 'v_review_due', '复验队列：P2 钉 transcript、P3 回一手、P4 实际值替换'),
  ('F3.6', 'table', 'stg_observation', '一行一个事实的登记格式'),
  ('F3.6', 'column', 'metric_registry.availability', '可得性四档 🟢🟡🔵⚪'),
  ('F3.6', 'column', 'metric_registry.fill_status', '填充状态'),
  ('F3.7', 'column', 'fct_quant.anchor', '原文短引'),
  ('F3.7', 'column', 'metric_registry.kou_jing', '口径写清测量级差异'),
  ('F3.7', 'column', 'fct_quant.conversion_assumption', '换算假设'),
  ('F3.7', 'column', 'fct_event.amount_type', '金额类型：一次 / 年化 / 多年上限 / 区间'),
  ('F3.8', 'column', 'fct_quant.superseded_by', '取代链'),
  ('F3.8', 'view', 'v_obs', '默认隐藏被取代行'),
  ('F3.9', 'column', 'fct_quant.snapshot_id', '快照 id = 文件名'),
  ('F3.9', 'file', 'pipeline/snapshots/', '来源原文本地快照'),
  ('F3.1', 'table', 'fct_quant', '类 1 量价'),
  ('F3.1', 'table', 'fct_event', '类 2 事件'),
  ('F3.1', 'table', 'fct_opinion', '类 3 观点'),
  ('F3.1', 'table', 'fct_frontier', '类 4 前沿'),
  ('F3.1', 'column', 'metric_registry.data_class', '指标属于哪类'),
  ('F3.1', 'column', 'stg_observation.routed_to', '按 data_class 路由'),
  ('F4.1', 'view', 'v_calendar', '排期 + 简报'),
  ('F4.1', 'view', 'v_metric_latest', '标题值 / 指引 / 上期'),
  ('F4.1', 'column', 'calendar.basis', '日期依据类型：公司公告 / 规则推定 / 估计 / 待定'),
  ('F4.2', 'column', 'metric_registry.signal_role', '信号角色：预测 / 预期基准 / 对账'),
  ('F4.2', 'file', 'pipeline/build_dashboard.py', '面板从库出图'),
  ('F4.3', 'column', 'observation_direction.direction', '↑↓→!— 方向判断'),
  ('F4.3', 'view', 'v_signal_latest', '节点最近方向'),
  ('F4.5', 'table', 'key_fact', '有作者的简报'),
  ('F4.5', 'column', 'key_fact.falsifier', '证伪条件'),
  ('F4.5', 'column', 'key_fact.status_line', '一句话现状'),
  ('F4.6', 'file', '13-术语表.csv', '内部名 → 界面名 → 层'),
  ('F4.6', 'file', 'pipeline/template.html', '整页下钻 + 面板'),
  ('F3.4', 'table', 'schema_doc', '每列字典'),
  ('F3.4', 'table', 'relation_doc', '表间关系'),
  ('F3.4', 'table', 'calc_rule', 'R1–R14'),
  ('F3.4', 'view', 'v_schema_coverage', '有值率 = 进度'),
  ('F3.4', 'check', '7c', '字典完整性'),
  ('F3.5', 'table', 'migration_log', '改库记录 + checksum'),
  ('F3.5', 'table', 'change_log', '字段级改动账'),
  ('F3.5', 'file', 'pipeline/migrations/', '每次改库一个脚本'),
  ('F3.5', 'check', '7g', '脚本 checksum'),
  ('F3.5', 'check', '7h', '根目录 CSV 漂移提醒'),
  ('F3.11', 'file', 'pipeline/SCHEMA.md', '由库生成'),
  ('F3.11', 'file', 'pipeline/schema_browser.html', '由库生成'),
  ('F4.7', 'table', 'thesis_node', '主线'),
  ('F4.7', 'table', 'decision_fork', '分叉'),
  ('F4.7', 'table', 'artifact_anchor', '产物锚点'),
  ('F4.7', 'view', 'v_column_origin', '反查某列来自哪一步决策'),
  ('F4.7', 'check', '7i', '锚点引用必须存在'),
  ('F3.12', 'file', 'pipeline/README.md', '与生产设计的关系：迁 Postgres 只改方言'),
  ('F3.3', 'column', 'metric_registry.frequency', '每指标天然频率（季 / 月 / 事件 / 周）'),
  ('F3.3', 'column', 'metric_registry.next_release', '下次发布日'),
  ('F3.3', 'column', 'metric_registry.next_release_basis', '依据分级：公司公告 / 规则推定 / 估计 / 待定'),
  ('F3.3', 'column', 'calendar.basis', '排期的日期依据类型'),
  ('F3.3', 'view', 'v_review_due', '复验队列按频率触发'),
]

def up(m):
    for nid, seq, title, q, c, rings, refs in NODES:
        m.insert('thesis_node', dict(node_id=nid, seq=seq, title=title, question=q, conclusion=c, rings=rings, doc_refs=refs, owner='B', status='draft'), basis=refs)
    for nid, seq, q, opts, chosen, why, ba, w, ref in FORKS:
        fid = f'F{nid[1]}.{seq}'
        m.insert('decision_fork', dict(fork_id=fid, node_id=nid, seq=seq, question=q, options=opts, chosen=chosen, rationale=why, before_after=ba, weight=w, log_ref=ref, owner='B', status='draft'), basis=ref)
    for i, (fid, kind, ref, how) in enumerate(ANCHORS, 1):
        m.insert('artifact_anchor', dict(anchor_id=f'a{i:03d}', fork_id=fid, kind=kind, ref=ref, how=how), basis='思路 ↔ 数据双向锚定')

