# -*- coding: utf-8 -*-
"""实体主表（doc21 §一 两轴）：layer 价值栈 × maturity。B 初稿。"""
E = [
 # entity_id, name, type, layer, maturity, track, country, ticker, in_book
 ('ent_nbis','Nebius Group','company','L2','public','neocloud','EU','NBIS',True),
 ('ent_rbrk','Rubrik','company','L4','public','数据安全 / AI 治理','US','RBRK',True),
 ('ent_fcel','FuelCell Energy','company','L1','public','数据中心电力','US','FCEL',True),
 ('ent_staa','STAAR Surgical','company',None,'public','医疗 ICL（非 AI）','US','STAA',True),
 ('ent_supx','SuperX AI','company','L2','public','AI 服务器整机','other','SUPX',True),
 ('ent_sndk','Sandisk','company','L1','public','NAND 存储','US','SNDK',True),
 ('ent_mu','Micron','company','L1','public','HBM / DRAM','US','MU',True),
 ('ent_intc','Intel','company','L1','public','CPU / 代工','US','INTC',True),
 ('ent_cien','Ciena','company','L1','public','光互连','US','CIEN',True),
 ('ent_mrvl','Marvell','company','L1','public','定制芯片 / 光 DSP','US','MRVL',True),
 ('ent_poet','POET Technologies','company','L1','public','光互连','US','POET',True),
 ('ent_amd','AMD','company','L1','public','加速器','US','AMD',True),
 ('ent_slmt','Brera Holdings','company',None,'public','加密（非 AI）','US','SLMT',True),
 ('ent_0679','亚洲电信科技','company',None,'public','电镀设备（非 AI）','HK','0679.HK',False),
 ('ent_book','13F 组合','index',None,'public','组合','US',None,True),
 ('ent_zte','中际旭创','company','L1','public','光互连','CN','300308.SZ',False),
 ('ent_eop','新易盛','company','L1','public','光互连','CN','300502.SZ',False),
 ('ent_optics_cn','中国光模块出口（赛道）','track','L1','public','光互连','CN',None,False),
 ('ent_customs','海关总署','institution','L1','public','光互连','CN',None,False),
 ('ent_hbm','HBM / CoWoS（赛道）','track','L1','public','存储 / 封装','other',None,False),
 ('ent_nvda','NVIDIA','company','L1','public','加速器','US','NVDA',False),
 ('ent_msft','Microsoft','company','L2','public','hyperscaler','US','MSFT',False),
 ('ent_googl','Alphabet','company','L2','public','hyperscaler','US','GOOGL',False),
 ('ent_amzn','Amazon','company','L2','public','hyperscaler','US','AMZN',False),
 ('ent_meta','Meta','company','L2','public','hyperscaler','US','META',False),
 ('ent_crwv','CoreWeave','company','L2','public','neocloud','US','CRWV',False),
 ('ent_iea','IEA','institution','L1','public','能源','other',None,False),
 ('ent_scale','Scale AI','company','L4','private','数据标注','US',None,False),
 ('ent_surge','Surge AI','company','L4','private','数据标注','US',None,False),
 ('ent_nyt_case','NYT v. OpenAI / Microsoft','institution','L4','public','版权诉讼','US',None,False),
 ('ent_reddit','Reddit','company','L4','public','数据授权','US','RDDT',False),
 ('ent_wiley','Wiley','company','L4','public','数据授权','US','WLY',False),
 ('ent_reflection','Reflection AI','company','L3','private','前沿模型','US',None,False),
 ('ent_cohere','Cohere','company','L3','private','企业 LLM','other',None,False),
 ('ent_openai','OpenAI','company','L3','private','前沿模型','US',None,False),
 ('ent_anthropic','Anthropic','company','L3','private','前沿模型','US',None,False),
 ('ent_xai','xAI','company','L3','private','前沿模型','US',None,False),
 ('ent_poolside','Poolside','company','L3','private','代码模型','US',None,False),
 ('ent_epoch','Epoch AI','institution','L3','research','算力计量','other',None,False),
 ('ent_aa','Artificial Analysis','institution','L3','research','第三方评测','other',None,False),
 ('ent_arc','ARC Prize','institution','L3','research','基准','US',None,False),
 ('ent_arena','LMArena','institution','L3','research','基准','US',None,False),
 ('ent_swebench','SWE-bench','institution','L3','research','基准','US',None,False),
 ('ent_hf','Hugging Face','company','L4','private','开源生态','US',None,False),
 ('ent_openrouter','OpenRouter','company','L4','private','推理路由','US',None,False),
 ('ent_google','Google（Gemini API）','company','L3','public','模型 API','US','GOOGL',False),
 ('ent_bis','BIS（美国商务部）','institution',None,'public','出口管制','US',None,False),
 ('ent_wh','White House','institution',None,'public','关税 / 232','US',None,False),
 ('ent_doj','DOJ','institution',None,'public','司法','US',None,False),
 ('ent_frontier_cap','前沿模型能力（赛道）','track','L3','research','前沿模型','other',None,False),
]
# 指标 → 实体（按 ticker_or_entity / name 关键词匹配；匹配不到的挂到赛道级）
MAP = {
 'NBIS':'ent_nbis','RBRK':'ent_rbrk','FCEL':'ent_fcel','STAA':'ent_staa','SUPX':'ent_supx','SNDK':'ent_sndk','MU':'ent_mu','INTC':'ent_intc','CIEN':'ent_cien','MRVL':'ent_mrvl','POET':'ent_poet','AMD':'ent_amd','SLMT':'ent_slmt','0679.HK':'ent_0679','组合':'ent_book',
 '中际旭创 300308.SZ':'ent_zte','新易盛 300502.SZ':'ent_eop','海关总署':'ent_customs','光模块（赛道）':'ent_optics_cn','HBM / CoWoS':'ent_hbm','NVDA（代理）':'ent_nvda','MSFT':'ent_msft','GOOGL':'ent_googl','AMZN':'ent_amzn','META':'ent_meta','MSFT / GOOGL / AMZN / META':['ent_msft','ent_googl','ent_amzn','ent_meta'],'云 GPU 市场':'ent_nvda','IEA':'ent_iea',
 '前沿数据':'ent_frontier_cap','Scale / Surge':['ent_scale','ent_surge'],'版权诉讼':['ent_nyt_case','ent_reddit','ent_wiley'],
 'Reflection AI':'ent_reflection','Reflection AI ↔ NBIS':['ent_reflection','ent_nbis'],'Cohere':'ent_cohere','OpenAI / Anthropic / xAI / Mistral 等':['ent_openai','ent_anthropic','ent_xai'],'AI 赛道一级':'ent_frontier_cap','Nvidia 系':['ent_nvda','ent_crwv','ent_nbis','ent_openai','ent_poolside'],'CRWV（NBIS 同业）':'ent_crwv','pre-IPO 池':'ent_frontier_cap','顶尖研究员':'ent_frontier_cap',
 '前沿模型（赛道）':['ent_epoch','ent_frontier_cap'],'Artificial Analysis':'ent_aa','arXiv / OpenAlex':'ent_frontier_cap','HuggingFace / GitHub':['ent_hf','ent_aa'],'榜单':['ent_swebench','ent_arc','ent_arena'],'前沿范式':'ent_frontier_cap',
 '企业 AI adoption':'ent_rbrk','推理定价':['ent_openai','ent_anthropic','ent_google'],'OpenRouter 等':'ent_openrouter','中国 AI 应用出海':'ent_frontier_cap',
 'BIS':['ent_bis','ent_wh'],'工信部 / 国务院':'ent_bis','能源 / 电网':'ent_iea','EU / 美各州':'ent_bis','安全事故':'ent_frontier_cap',
}
